name: Docker Image CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for temporary use only
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      run: docker build . --file Dockerfile --tag tmp:latest
    - name: Build the Docker image for tag release
      if: startsWith(github.ref, 'refs/tags/')
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest
    - name: Docker Login
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag latest docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest wseresearch/${{ secrets.DOCKER_IMAGE_NAME }}:latest
    - name: Tag docker image version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest "wseresearch/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}"
    - name: Push latest docker image
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push wseresearch/${{ secrets.DOCKER_IMAGE_NAME }}:latest
    - name: Push docker image version
      if: startsWith(github.ref, 'refs/tags/')
      run: docker push "wseresearch/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}"
    - name: Init update
      if: startsWith(github.ref, 'refs/tags/')
      uses: WSE-research/docker-service-updater@v0.2.1
      with:
        updater_host: ${{ secrets.UPDATER_HOST }}
        api_key: ${{ secrets.API_KEY }}
